# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 5) do

  create_table "categories", :force => true do |t|
    t.column "name", :string
  end

  create_table "classifieds", :force => true do |t|
    t.column "title", :string
    t.column "price", :float
    t.column "location", :string
    t.column "description", :text
    t.column "email", :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "category_id", :integer
    t.column "content_type", :string, :default => "image/png"
    t.column "picture", :binary
    t.column "user_id", :integer
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data", :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "sessions_session_id_index"

  create_table "users", :force => true do |t|
    t.column "login", :string
    t.column "password", :string
    t.column "email", :string
  end

end
